### ISSUE TITLE
Build fails on amd64 -- getline()

### ISSUE THREAD

**Issue by gheja** [gheja/gbdk#13]
Build still fails on amd64, see #6.

**Comment by NEMS1996** [comment]
> getline() uses `_IO_ssize_t`, and that is `long` on amd64 opposed to `int` on i386.

May I know how u overcome this error when compiling on amd64?

**Comment by gheja** [comment]
I believe it was only a type problem, I searched and replaced it, see commit c44d5c84dc29beb49bc7f7689c08679e434a4829 I mentioned in the close comment.
