### ISSUE TITLE
Work together with GBDK-N?

### ISSUE THREAD

**Issue by clobber** [gheja/gbdk#17]
You're supporting the old GBDK which is based around a 15+ year old version of the compiler/assembler/linker in an ancient SDCC, full of bugs.

[GBDK-N](https://github.com/rotmoset/gbdk-n) has been updated to work with the latest SDCC suite and is good moving forward to get people off of such an old compiler. Maybe it's a good idea to combine efforts so people, oblivious to an updated library, such as those doing homebrew in the [gbdev scene](http://gbdev.gg8.se/forums/) can start using a modern set of tools?

**Comment by gheja** [comment]
The GBDK-N is indeed a great suite but it has a few issues that are not present in this ancient GBDK version, one for example is the [bank switching/banked code support](https://github.com/rotmoset/gbdk-n/issues/5) and this is unfortunately a serious one as it limits the final binary to 64 kilobytes.

I am not actively developing this project or back-porting the changes (I don't really have the expertise this project requires), I just merely want to adapt it to modern OS-es and compilers to have the suite working for a bit longer.

**Comment by PikalaxALT** [comment]
Maintaining the ancient compiler has its own merits, in that disassembly projects such as [Keitai Denjuu Telefang](https://github.com/pikalaxalt/telefang_gb) would want to evolve into decompilation projects, in which the immediate goal would be to generate C source code that compiles to a matching ROM.  In this sense, the correct compiler is key.  I have reason to believe, based on comparison of math functions, that Telefang was compiled from some version of gbdk.

**Comment by gheja** [comment]
Thanks for your comments!

In 2021 I added a note in the readme about [GBDK-2020](https://github.com/gbdk-2020/gbdk-2020) that was mentioned on the SourceForge page - I just checked it and seems to be still alive (the latest commit was 2 days ago!).
