### ISSUE TITLE
Error compiling on cygwin x86-64 (missing typedef?)

### ISSUE THREAD

**Issue by PikalaxALT** [gheja/gbdk#19]
Below is the relevant portion of the error dump.  From this I suspect that `_IO_ssize_t` is not defined within the context of aslink.h.

    make[4]: Entering directory '~/gbdk/sdcc/link/z80'
    mkdir -p obj/-z80
    gcc -c -ggdb -O2 -pipe -Wall  -I. -I../.. -I../../support/Util  -DINDEXLIB -DMLH_MAP -DUNIX -DSDK -funsigned-char -DUNIX -I../../as/z80 -I../../support/Util  -o obj/-z80/lkarea.o lkarea.c
    In file included from lkarea.c:13:0:
    ../../as/z80/string.h:9:12: warning: conflicting types for built-in function ‘strlen’
     extern int strlen();
                ^
    In file included from lkarea.c:14:0:
    aslink.h:638:8: error: unknown type name ‘_IO_ssize_t’
     extern _IO_ssize_t getline(char **__restrict __lineptr, size_t *__restrict __n, FILE *__restrict __stream);
            ^
    aslink.h:638:20: error: conflicting types for ‘getline’
     extern _IO_ssize_t getline(char **__restrict __lineptr, size_t *__restrict __n, FILE *__restrict __stream);
                        ^
    In file included from /usr/include/stdio.h:29:0,
                     from lkarea.c:12:
    /usr/include/sys/stdio.h:35:9: note: previous declaration of ‘getline’ was here
     ssize_t _EXFUN(getline, (char **, size_t *, FILE *));
             ^
    make[4]: *** [Makefile:33: obj/-z80/lkarea.o] Error 1

**Comment by IoIxDButStronger** [comment]
Use this updated version: https://github.com/andreasjhkarlsson/gbdk-n

**Comment by gheja** [comment]
I am sorry for the very late reply, I found what the problem was and will fix it in a commit to keep this version of GBDK running a bit more.

**Comment by IoIxD** [comment]
I don't remember much of this project but if my memory serves correct you may as well just merge that repo i linked back to yours.

**Comment by gheja** [comment]
Thank you, but GBDK-n has many differences (ie. banking is not supported there) and I'd like to keep this as it was when the original developer left the project - I think people might still have games that could be built with this version.
