### ISSUE TITLE
Fix INT8 that was unsigned instead of signed

### ISSUE THREAD

**Issue by gheja** [gheja/gbdk#21]
https://github.com/andreasjhkarlsson/gbdk-n/pull/13/commits/70da9c076552396d6466902e4a5910c5d6e836ea

https://github.com/andreasjhkarlsson/gbdk-n/pull/13

Thanks @flozz for bringing this to my attention.

**Comment by flozz** [comment]
The old SDCC version in this repository is not impacted (I have not this issue when I compile my GB programs with the version of this repository), but if you plan to update SDCC, you will have the issue :)

**Comment by gheja** [comment]
Oh, thanks! Good to know :)
