### ISSUE TITLE
error: number of arguments doesn't match prototype -- getline()

### ISSUE THREAD

**Issue by gheja** [gheja/gbdk#6]
asmain.c: In function 'main':
asmain.c:291:3: error: too few arguments to function 'getline'
In file included from asmain.c:15:0:
/usr/include/stdio.h:671:20: note: declared here
make[2]: **\* [asmain.o] Error 1
make[2]: Leaving directory '/home/builder/project/sdcc/as/mcs51'
make[2]: Entering directory '/home/builder/project/sdcc/as'

lklex.c: In function 'getline':
lklex.c:425:1: error: number of arguments doesn't match prototype
In file included from lklex.c:16:0:
/usr/include/stdio.h:671:20: error: prototype declaration
make[4]: **\* [obj/-z80/lklex.o] Error 1
make[4]: Leaving directory '/home/builder/project/sdcc/link/z80'

... and a lot more instances of these messages ...

**Comment by NEMS1996** [comment]
So is there any workaround for this or is it a deadlock?

**Comment by gheja** [comment]
I believe I fixed this in commit 2ffb56732a65d862248a2b7ddb94c110d424547 I mentioned in the close comment.
